/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package opdrachten;

import java.time.LocalDateTime;

import opdrachten.Adapter.SmsAdapter;
import opdrachten.Adapter.SmsMock;
import opdrachten.Domain.Movie;
import opdrachten.Domain.MovieScreening;
import opdrachten.Domain.MovieTicket;
import opdrachten.Domain.Order;
import opdrachten.Domain.TicketExportFormat;
import opdrachten.Observer.OrderSubscriber;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void hello() {
        Movie movie = new Movie("Lord of the Rings");
        MovieScreening movieScreening = new MovieScreening(movie, LocalDateTime.now(), 20.00);
        MovieTicket ticketMaurice = new MovieTicket(movieScreening, true, 4, 12);
        MovieTicket ticketLauran = new MovieTicket(movieScreening, true, 4, 13);
        MovieTicket ticketRamon = new MovieTicket(movieScreening, true, 4, 14);

        Order order = new Order(1, true);

        order.addSeatReservation(ticketMaurice);
        order.addSeatReservation(ticketLauran);
        order.addSeatReservation(ticketRamon);

        SmsMock smsMock = new SmsMock();
        SmsAdapter smsAdapter = new SmsAdapter(smsMock, "+31 6 81139297"); 

        OrderSubscriber orderSubscriber = new OrderSubscriber(smsAdapter);
        order.subscribe(orderSubscriber);
        order.submit();
        

    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        hello();
    }
}
